version: '3.8'

services:
  webapi:
    build:
      context: ..
      dockerfile: RealEstateListingApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
